# Stage 1: Build frontend assets
FROM node:20-slim AS frontend
WORKDIR /app
COPY package.json vite.config.js tailwind.config.js postcss.config.cjs ./
COPY resources resources
RUN npm install && npm run build

# Stage 2: Final Image
FROM php:8.2-fpm-alpine
RUN apk add --no-cache nginx supervisor shadow libpng-dev libjpeg-turbo-dev freetype-dev postgresql-dev

# Install PHP Extensions
RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd

WORKDIR /var/www/html
COPY . .
COPY --from=frontend /app/public/build ./public/build

# Setup Supervisor
COPY docker/vps.conf /etc/supervisord.conf
COPY docker/nginx.conf /etc/nginx/nginx.conf

RUN chown -R www-data:www-data /var/www/html
EXPOSE 80 8081
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]