FROM php:8.2-fpm-alpine

# Only install what Reverb needs
RUN apk add --no-cache linux-headers
RUN docker-php-ext-install sockets

WORKDIR /var/www/html
COPY . .
RUN composer install --no-dev --optimize-autoloader

# Run Reverb directly as the main process
EXPOSE 8081
CMD ["php", "artisan", "reverb:start", "--host=0.0.0.0", "--port=8081"]