[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0

[program:php-fpm]
command=php-fpm

[program:nginx]
command=nginx -g "daemon off;"

[program:reverb]
# Reverb must use a different port than the web server
command=php /var/www/html/artisan reverb:start --host=0.0.0.0 --port=8081
user=www-data
autorestart=true